# Generated by Django 3.1.5 on 2021-02-13 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0004_auto_20210213_1202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
    ]
